-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS qualidade.answer_group_items
(
    answer_group_id bigint NOT NULL,
    answer_id bigint NOT NULL,
    ordem smallint NOT NULL,
    CONSTRAINT answer_group_items_pkey PRIMARY KEY (answer_group_id, answer_id),
    CONSTRAINT answer_group_items_answer_id_key UNIQUE (answer_id)
);

CREATE TABLE IF NOT EXISTS qualidade.answer_groups
(
    id bigserial NOT NULL,
    form_id bigint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT answer_groups_pkey PRIMARY KEY (id),
    CONSTRAINT uq_answer_group UNIQUE (form_id, nome)
);

CREATE TABLE IF NOT EXISTS qualidade.answer_result
(
    id bigserial NOT NULL,
    answer_id bigint NOT NULL,
    control_id bigint NOT NULL,
    resposta text COLLATE pg_catalog."default" NOT NULL,
    limits_answer_id bigint,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT answer_result_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS qualidade.answers
(
    id bigserial NOT NULL,
    form_id bigint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    categorie_id bigint,
    CONSTRAINT answers_pkey PRIMARY KEY (id),
    CONSTRAINT unique_nome_form_answers UNIQUE (nome, form_id)
);

CREATE TABLE IF NOT EXISTS qualidade.breaks_forms
(
    id bigserial NOT NULL,
    form_id bigint NOT NULL,
    hora_inicio timestamp without time zone,
    hora_fim timestamp without time zone,
    motivo text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT breaks_forms_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS qualidade.breaks_machines
(
    id bigserial NOT NULL,
    machine_id bigint NOT NULL,
    hora_inicio timestamp without time zone,
    hora_fim timestamp without time zone,
    motivo text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT breaks_machines_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS qualidade.categories_answers
(
    id bigserial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT categories_answers_pkey PRIMARY KEY (id),
    CONSTRAINT unique_nome_categories_answers UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS qualidade.control_status
(
    control_id bigint NOT NULL,
    status_id bigint NOT NULL,
    CONSTRAINT control_status_pkey PRIMARY KEY (control_id, status_id)
);

CREATE TABLE IF NOT EXISTS qualidade.controls
(
    id bigserial NOT NULL,
    form_id bigint NOT NULL,
    user_id bigint NOT NULL,
    file_id bigint NOT NULL,
    observacao text COLLATE pg_catalog."default",
    data_emissao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT controls_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS qualidade.form_draft
(
    form_id bigint NOT NULL,
    rascunho_data json NOT NULL,
    CONSTRAINT form_draft_pkey PRIMARY KEY (form_id)
);

CREATE TABLE IF NOT EXISTS qualidade.form_time
(
    form_id bigint NOT NULL,
    tempo_execucao time without time zone NOT NULL,
    tempo_tolerancia time without time zone NOT NULL,
    tempo_antecedencia time without time zone NOT NULL DEFAULT '00:05:00'::interval,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT form_time_pkey PRIMARY KEY (form_id)
);

CREATE TABLE IF NOT EXISTS qualidade.forms
(
    id bigserial NOT NULL,
    section_id bigint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT forms_pkey PRIMARY KEY (id),
    CONSTRAINT unique_nome_section_forms UNIQUE (nome, section_id)
);

CREATE TABLE IF NOT EXISTS qualidade.limits_answers
(
    id bigserial NOT NULL,
    answer_id bigint NOT NULL,
    limit_max numeric(19, 4),
    limit_min numeric(19, 4),
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT limits_answers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS qualidade.limits_machine_answers
(
    id bigserial NOT NULL,
    machine_answer_id bigint NOT NULL,
    limit_max numeric(19, 4),
    limit_min numeric(19, 4),
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT limits_machine_answers_pkey PRIMARY KEY (id),
    CONSTRAINT unique_answer_id_limits_machine_answers UNIQUE (machine_answer_id)
);

CREATE TABLE IF NOT EXISTS qualidade.machine_answer_result
(
    id bigserial NOT NULL,
    machine_id bigint NOT NULL,
    answer_id bigint NOT NULL,
    control_id bigint NOT NULL,
    resposta text COLLATE pg_catalog."default" NOT NULL,
    limits_answer_id bigint,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT machine_answer_result_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS qualidade.machine_answers
(
    id bigserial NOT NULL,
    machine_id bigint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default",
    descricao text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT machine_answers_pkey PRIMARY KEY (id),
    CONSTRAINT unique_nome_machineid_machine_answers UNIQUE (nome, machine_id)
);

CREATE TABLE IF NOT EXISTS qualidade.machines
(
    id bigserial NOT NULL,
    form_id bigint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT machines_pkey PRIMARY KEY (id),
    CONSTRAINT unique_nome_form_machines UNIQUE (nome, form_id)
);

CREATE TABLE IF NOT EXISTS qualidade.repairer_answer_result
(
    answer_result_id bigint NOT NULL,
    user_id bigint NOT NULL,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT repairer_answer_result_pkey PRIMARY KEY (answer_result_id, user_id)
);

CREATE TABLE IF NOT EXISTS qualidade.sections
(
    id bigserial NOT NULL,
    employer_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT section_pkey PRIMARY KEY (id),
    CONSTRAINT unique_nome_employer_sections UNIQUE (nome, employer_id)
);

CREATE TABLE IF NOT EXISTS qualidade.status
(
    id bigserial NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT status_pkey PRIMARY KEY (id),
    CONSTRAINT unique_nome_status UNIQUE (nome)
);

ALTER TABLE IF EXISTS qualidade.answer_group_items
    ADD CONSTRAINT answer_group_items_answer_group_id_fkey FOREIGN KEY (answer_group_id)
    REFERENCES qualidade.answer_groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS qualidade.answer_group_items
    ADD CONSTRAINT answer_group_items_answer_id_fkey FOREIGN KEY (answer_id)
    REFERENCES qualidade.answers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS answer_group_items_answer_id_key
    ON qualidade.answer_group_items(answer_id);


ALTER TABLE IF EXISTS qualidade.answer_groups
    ADD CONSTRAINT fk_answer_groups_form FOREIGN KEY (form_id)
    REFERENCES qualidade.forms (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS qualidade.answer_result
    ADD CONSTRAINT answers_fkey FOREIGN KEY (answer_id)
    REFERENCES qualidade.answers (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS qualidade.answer_result
    ADD CONSTRAINT fk_answer_result_control FOREIGN KEY (control_id)
    REFERENCES qualidade.controls (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS qualidade.answers
    ADD CONSTRAINT categories_answers_fkey FOREIGN KEY (categorie_id)
    REFERENCES qualidade.categories_answers (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS qualidade.answers
    ADD CONSTRAINT forms_fkey FOREIGN KEY (form_id)
    REFERENCES qualidade.forms (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_answers_ativos
    ON qualidade.answers(form_id);


ALTER TABLE IF EXISTS qualidade.breaks_forms
    ADD CONSTRAINT forms_fkey FOREIGN KEY (form_id)
    REFERENCES qualidade.forms (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS qualidade.breaks_machines
    ADD CONSTRAINT machines_fkey FOREIGN KEY (machine_id)
    REFERENCES qualidade.machines (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS qualidade.control_status
    ADD CONSTRAINT controls_fkey FOREIGN KEY (control_id)
    REFERENCES qualidade.controls (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS qualidade.control_status
    ADD CONSTRAINT status_fkey FOREIGN KEY (status_id)
    REFERENCES qualidade.status (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
	

ALTER TABLE IF EXISTS qualidade.controls
    ADD CONSTRAINT forms_fkey FOREIGN KEY (form_id)
    REFERENCES qualidade.forms (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_controls_form
    ON qualidade.controls(form_id);


ALTER TABLE IF EXISTS qualidade.form_draft
    ADD CONSTRAINT forms_fkey FOREIGN KEY (form_id)
    REFERENCES qualidade.forms (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS form_draft_pkey
    ON qualidade.form_draft(form_id);


ALTER TABLE IF EXISTS qualidade.form_time
    ADD CONSTRAINT forms_fkey FOREIGN KEY (form_id)
    REFERENCES qualidade.forms (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS form_time_pkey
    ON qualidade.form_time(form_id);


ALTER TABLE IF EXISTS qualidade.forms
    ADD CONSTRAINT section_fkey FOREIGN KEY (section_id)
    REFERENCES qualidade.sections (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_forms_ativos
    ON qualidade.forms(section_id);


ALTER TABLE IF EXISTS qualidade.limits_answers
    ADD CONSTRAINT answers_fkey FOREIGN KEY (answer_id)
    REFERENCES qualidade.answers (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS qualidade.limits_machine_answers
    ADD CONSTRAINT answers_fkey FOREIGN KEY (machine_answer_id)
    REFERENCES qualidade.machine_answers (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS unique_answer_id_limits_machine_answers
    ON qualidade.limits_machine_answers(machine_answer_id);


ALTER TABLE IF EXISTS qualidade.machine_answer_result
    ADD CONSTRAINT fk_machine_answer_result_control FOREIGN KEY (control_id)
    REFERENCES qualidade.controls (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS qualidade.machine_answer_result
    ADD CONSTRAINT machine_answers_fkey FOREIGN KEY (answer_id)
    REFERENCES qualidade.answers (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS qualidade.machine_answer_result
    ADD CONSTRAINT machines_fkey FOREIGN KEY (machine_id)
    REFERENCES qualidade.machines (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS qualidade.machine_answers
    ADD CONSTRAINT machines_fkey FOREIGN KEY (machine_id)
    REFERENCES qualidade.machines (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS qualidade.machines
    ADD CONSTRAINT forms_fkey FOREIGN KEY (form_id)
    REFERENCES qualidade.forms (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_machines_ativas
    ON qualidade.machines(form_id);


ALTER TABLE IF EXISTS qualidade.repairer_answer_result
    ADD CONSTRAINT answer_result_fkey FOREIGN KEY (answer_result_id)
    REFERENCES qualidade.answer_result (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


END;