-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS unico.cost_centers
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cost_centers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS unico.credentials
(
    id bigserial NOT NULL,
    user_id bigserial NOT NULL,
    system_id bigserial NOT NULL,
    senha_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status smallint NOT NULL DEFAULT 1,
    data_ultimo_login timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT credentials_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS unico.credentials_locations
(
    credential_id bigint NOT NULL,
    location_id bigint NOT NULL,
    CONSTRAINT credentials_locations_pkey PRIMARY KEY (credential_id, location_id)
);

CREATE TABLE IF NOT EXISTS unico.credentials_roles
(
    credential_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT credentials_roles_pkey PRIMARY KEY (credential_id, role_id)
);

CREATE TABLE IF NOT EXISTS unico.departments
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT departments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS unico.employees
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    company_number integer,
    register_number integer,
    registration_number integer,
    person_id character varying(50) COLLATE pg_catalog."default",
    person_name character varying(255) COLLATE pg_catalog."default",
    hire_date date,
    dismissal_date date,
    hash character varying(64) COLLATE pg_catalog."default",
    employer_id character varying(50) COLLATE pg_catalog."default",
    department_id character varying(50) COLLATE pg_catalog."default",
    job_position_id character varying(50) COLLATE pg_catalog."default",
    workstation_group_id character varying(50) COLLATE pg_catalog."default",
    workshift_id character varying(50) COLLATE pg_catalog."default",
    cost_center_id character varying(50) COLLATE pg_catalog."default",
    synced_at timestamp without time zone DEFAULT now(),
    CONSTRAINT employees_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS unico.employers
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    trading_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT employers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS unico.face_descriptors
(
    user_id bigint NOT NULL,
    descriptor jsonb NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT face_descriptors_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS unico.files
(
    id bigserial NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nome_original character varying(255) COLLATE pg_catalog."default",
    extensao character varying(20) COLLATE pg_catalog."default",
    mime_type character varying(100) COLLATE pg_catalog."default",
    tamanho bigint,
    conteudo bytea NOT NULL,
    hash_sha256 character varying(64) COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT files_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS unico.job_positions
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT job_positions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS unico.locations
(
    id bigserial NOT NULL,
    employer_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT locations_pkey PRIMARY KEY (id),
    CONSTRAINT locations_employer_id_key UNIQUE (employer_id),
    CONSTRAINT unique_nome_employer_locations UNIQUE (nome, employer_id)
);

CREATE TABLE IF NOT EXISTS unico.roles
(
    id bigserial NOT NULL,
    system_id bigint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT unique_nome_system_roles UNIQUE (nome, system_id)
);

CREATE TABLE IF NOT EXISTS unico.sessions
(
    id bigserial NOT NULL,
    credential_id bigserial NOT NULL,
    refreshtoken text COLLATE pg_catalog."default" NOT NULL,
    expira timestamp with time zone NOT NULL,
    revogado boolean NOT NULL DEFAULT false,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS unico.sync_logs
(
    id bigserial NOT NULL,
    started_at timestamp without time zone NOT NULL,
    finished_at timestamp without time zone NOT NULL,
    duration_ms bigint NOT NULL,
    inserted integer NOT NULL,
    updated integer NOT NULL,
    removed integer NOT NULL,
    total_api integer NOT NULL,
    total_before integer NOT NULL,
    success boolean NOT NULL,
    error text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT sync_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS unico.systems
(
    id bigserial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    url character varying(50) COLLATE pg_catalog."default",
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT systems_pkey PRIMARY KEY (id),
    CONSTRAINT unique_nome_systems UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS unico.users
(
    id bigserial NOT NULL,
    employee_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status smallint NOT NULL DEFAULT 1,
    data_criacao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT unique_email_employee_users UNIQUE (email, employee_id),
    CONSTRAINT unique_employee_users UNIQUE (employee_id),
    CONSTRAINT unique_username_employee_users UNIQUE (username, employee_id)
);

CREATE TABLE IF NOT EXISTS unico.workshifts
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT workshifts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS unico.workstation_groups
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT workstation_groups_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS unico.credentials
    ADD CONSTRAINT systems_fkey FOREIGN KEY (system_id)
    REFERENCES unico.systems (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS unico.credentials
    ADD CONSTRAINT users_fkey FOREIGN KEY (user_id)
    REFERENCES unico.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_credentials_user
    ON unico.credentials(user_id);


ALTER TABLE IF EXISTS unico.credentials_locations
    ADD CONSTRAINT credentials_fkey FOREIGN KEY (credential_id)
    REFERENCES unico.credentials (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS unico.credentials_locations
    ADD CONSTRAINT locations_fkey FOREIGN KEY (location_id)
    REFERENCES unico.locations (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS unico.credentials_roles
    ADD CONSTRAINT credentials_fkey FOREIGN KEY (credential_id)
    REFERENCES unico.credentials (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS unico.credentials_roles
    ADD CONSTRAINT roles_fkey FOREIGN KEY (role_id)
    REFERENCES unico.roles (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS unico.face_descriptors
    ADD CONSTRAINT face_descriptors_user_fkey FOREIGN KEY (user_id)
    REFERENCES unico.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS face_descriptors_pkey
    ON unico.face_descriptors(user_id);


ALTER TABLE IF EXISTS unico.locations
    ADD CONSTRAINT employers_fkey FOREIGN KEY (employer_id)
    REFERENCES unico.employers (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS locations_employer_id_key
    ON unico.locations(employer_id);


ALTER TABLE IF EXISTS unico.roles
    ADD CONSTRAINT systems_fkey FOREIGN KEY (system_id)
    REFERENCES unico.systems (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS unico.sessions
    ADD CONSTRAINT credentials_fkey FOREIGN KEY (credential_id)
    REFERENCES unico.credentials (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_sessions_credential
    ON unico.sessions(credential_id);

END;